### PR TITLE
Bridge Changes

### PR DESCRIPTION
**Pull request by Whitey789**
Mapmerge came through on me. This has taken WAAAYYY too long. 
New Bridge - http://www.unbound-travels.com/showthread.php?4138-Bridge-Changes
Mostly detailed there.
Small shuttle change - http://gyazo.com/3ff29b118857b069be87aa1bb9a60fd8
Code-Blue Change - http://gyazo.com/5dc10199bb943b02cca9a3bfa17ad45e

### CODE REVIEW

**Comment by Lorwp** [comment]
Looks good, except for travis at least. Though why is there two sections of the Shuttle holding cells?

**Comment by Whitey789** [comment]
Travis.. What the hell are you doing, Travis? 
Anyway, just an actual cell to stop people from running out because lul

**Comment by Lorwp** [comment]
```The command "DreamMaker baystation12.dme" exited with 255.```
Would that have to do with anything?

**Comment by Whitey789** [comment]
I have no idea. Forgot mousse.

**Comment by Lorwp** [comment]
*Squeek*

**Pull request merged**
