### PR TITLE
No more park, new AI location, new Blueshield and Secretary locations.

### PR DESCRIPTION
**Pull request by W3bster**
-Arrivals lounge removed. Replaced with two-way arrivals hallways.
-Park wiped. Replaced with whole new AI area and crew lounge.
-Bridge reworked, with AI now removed. Blueshield's office moved inside.
-Secretary's office also moved in the empty AI area.
-Renamed areas for the new areas.
-Fixed small problem with new stairs.
-Fixed Central Command mapping.

### CODE REVIEW

**Comment by Lorwp** [comment]
*A moment of silence, for the park*

**Comment by Codingale** [comment]
Perhaps a bit more talk about it, the AI core on the first floor we both disagree with. The park is a bit of a waste but the AI can go elsewhere.. I don't like mapping changes that much as things change way to fast and go crazy though.. the bar from BestRP still makes me upset.. I like it the way it is now.

I think Whitey789 can map as I talk to them about the changes and we talk with others to come to an agreement and it's less dramatic of a change most of the times. Bug fixes for maps are fine for me, but too much at once personally upsets me.

**Comment by W3bster** [comment]
Dunno whom you're talking about when you say "Both". As for i find it a wondeful idea to have the AI at the core of the station and not some faraway non visited place. But eh. It was a concept.

**Comment by Codingale** [comment]
"we both", as in I and Jamie, remember the dev chat?

**Pull request closed without merging**
