### PR TITLE
VR Pod base, IPC Rebooting, Organ fix

### PR DESCRIPTION
**Pull request by TehFlaminTaco**
Added the base code for VR pods, not yet implemented.
Attaching an IPC's head re-boots it, without giving them X-RAY
Organs falling off aren't buggy and somewhat crashy.

### CODE REVIEW

**Comment by jamiedigweed** [comment]
Travis done failed :[

**Comment by Lorwp** [comment]
Training  Simulator? How would that work?

**Comment by TehFlaminTaco** [comment]
Yeah, This is the start. It's all the base code for it, I just need to iron out the bugs and specialize it. I'm just putting the code in because I have it laying around.

**Comment by Lorwp** [comment]
@TehFlaminTaco I think it may be best if you just do your best to make sure it actually compiles for  now.

**Pull request merged**
